spring.application.name=mycoolapp
server.port=8080
coach.name=Johnny Bravo
management.endpoints.web.exposure.include=*
# management.endpoints.web.exposure.exclude=health,info
management.info.env.enabled=true
info.app.name=SUPER COOL APP
info.app.description=A crazy fun App!
info.app.version=1.0.0