spring.application.name=mycoolapp
management.endpoints.web.exposure.include=*
# management.endpoints.web.exposure.exclude=health,info
management.info.env.enabled=true
info.app.name=SUPER COOL APP
info.app.description=A crazy fun App!
info.app.version=1.0.0

coach.name=Coach
team.name=L4D2 Club

#
# Change Spring Boot embedded server port
#
server.port=7070
server.servlet.context-path=/mycoolapp